{{- if .Values.tiles.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lulc-helm.fullname" . }}-azure-monitor-secrets
data:
  activeDirectoryClientId: {{ .Values.tilesScaler.env.activeDirectoryClientId | b64enc }}
  activeDirectoryClientPassword: {{ .Values.tilesScaler.env.activeDirectoryClientPassword | b64enc }}
{{- end }}
