repos:
    -
        repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.9.0
        hooks:
            - id: isort
              language_version: python3.8
    -
        repo: 'https://github.com/psf/black'
        rev: 21.6b0
        hooks:
            - id: black
              args: ['--safe']
              language_version: python3.8
    -
        repo: https://gitlab.com/PyCQA/flake8
        rev: 3.9.2
        hooks:
            - id: flake8
              language_version: python3.8
              args: [
                  # E501 let black handle all line length decisions
                  # W503 black conflicts with "line break before operator" rule
                  # E203 black conflicts with "whitespace before ':'" rule
                  '--ignore=E501,W503,E203,F841']
    -
        repo: 'https://github.com/chewse/pre-commit-mirrors-pydocstyle'
        # 2.1.1
        rev: v2.1.1
        hooks:
            - id: pydocstyle
              language_version: python3.8
              args: [
                 # Check for docstring presence only
                 '--select=D1',
                 # Don't require docstrings for tests
                 '--match=(?!test).*\.py']

    -
        repo: https://github.com/pre-commit/mirrors-mypy
        rev: 'v0.902'
        hooks:
            - id: mypy
              args: ['--no-strict-optional', '--ignore-missing-imports']
