version: '3'

services:
  tiler:
    build:
      context: ./tiles
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REQUEST_PAYER=requester
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PORT=8000
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - WORKERS_PER_CORE=1
      - MOSAIC_BACKEND=dynamodb://
      - MOSAIC_HOST=us-west-2/ds-mosaics-labs

  db:
    image: postgis/postgis:12-3.0
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
