version: '3'

services:
    api:
        build: ./services/api/
        depends_on:
            - postgis
        ports:
            - "2000:2000"
        environment:
            - PORT=2000
            - TileUrl=http://localhost:8000
            - SigningSecret=dev-signing-secret
            - Postgres=postgres://lulc:postgrespass@postgis:5432/lulc

    socket:
        build: ./services/socket/
        ports:
            - "1999:1999"
        environment:
            - PORT=1999
            - SigningSecret=dev-signing-secret

    tiler:
        build: ./services/tiles/
        depends_on:
            - cache
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - MOSAIC_BACKEND=sqlite:///
            - MOSAIC_HOST=/tmp/data/mosaics.db
            - CACHE_ENDPOINT=redis://host.docker.internal:6379

    postgis:
        image: postgis/postgis:12-3.1
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=lulc
            - POSTGRES_PASSWORD=postgrespass

    cache:
        image: redis:latest
        ports:
            - 6379:6379

