version: '3'

services:
    api:
        platform: linux/amd64
        build: ./services/api/
        command: sh -c "sleep 5; npm run dev"
        restart: always
        links:
            - postgis
        depends_on:
            - migration
        ports:
            - "2000:2000"
        environment:
            - PORT=2000
            - TileUrl=http://tiler:8000
            - PcTileUrl=https://planetarycomputer-staging.microsoft.com
            - Postgres=postgres://docker:docker@postgis:5432/gis
            - AZURE_STORAGE_CONNECTION_STRING

    stac:
        platform: linux/amd64
        build: ./services/stac/
        command: sh -c "sleep 5; npm run dev"
        restart: always
        links:
            - postgis
        depends_on:
            - migration
        ports:
            - "2001:2001"
        environment:
            - Postgres=postgres://docker:docker@postgis:5432/gis

    postgis:
        platform: linux/amd64
        image: kartoza/postgis:13.0
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - ALLOW_IP_RANGE=0.0.0.0/0
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASS=docker
            - POSTGRES_MULTIPLE_EXTENSIONS="postgis","uuid-ossp"

    socket:
        platform: linux/amd64
        build: ./services/socket/
        ports:
            - "1999:1999"
        environment:
            - PORT=1999
            - API=http://api:2000

    tiler:
        platform: linux/amd64
        build: ./services/tiles/
        depends_on:
            - cache
        ports:
            - 8000:8000
        environment:
            - TITILER_API_DEBUG=TRUE
            - PORT=8000
            - MOSAIC_BACKEND=sqlite:///
            - MOSAIC_HOST=/tmp/data/mosaics.db
            - CACHE_ENDPOINT=redis://host.docker.internal:6379

    cache:
        image: redis:latest
        ports:
            - 6379:6379

    migration:
        platform: linux/amd64
        build: ./services/api
        command: sh -c "pgstac --dsn $Postgres pgready && npx knex migrate:latest && pgstac --dsn $Postgres migrate"
        links:
            - postgis
        ports:
            - "2001:2001"
        depends_on:
            - postgis
        environment:
            - PORT=2001
            - Postgres=postgres://docker:docker@postgis:5432/gis
