#! /bin/bash

set -euo pipefail

export SigningSecret='i-am-a-dev-secret'

if echo '\l' | psql -U postgres lulc > /dev/null; then
    echo "ok - postgres lulc database exists"
else
    echo "
        CREATE DATABASE lulc;
    " | psql -U postgres
fi

killall -9 node || true

# API Bootstrapping
npm --prefix ./services/api/ install
npm --prefix ./services/api/ run doc
npm --prefix ./services/socket/ install

npm --prefix ./services/api/ run dev&

# Router Bootstrapping
npm --prefix ./services/socket/ run dev&

sleep 5

# Data Population
TEST=compose node test/flow.test.js

# GPU Bootstrapping
cd ./services/gpu/
python3 -m venv venv
source ./venv/bin/activate
pip install -r requirements.txt

export API='http://localhost:2000'
export SOCKET='http://localhost:1999'
export MODEL_ID='1'
python worker.py

wait
