#! /bin/bash

set -euo pipefail

export SigningSecret='i-am-a-dev-secret'

if echo '\l' | psql -U postgres lulc > /dev/null; then
    echo "ok - postgres lulc database exists"
else
    echo "
        CREATE DATABASE lulc;
    " | psql -U postgres
fi

killall -9 node

# API Bootstrapping
npm --prefix ./services/api/ install
npm --prefix ./services/api/ run doc
npm --prefix ./services/api/ install

npm --prefix ./services/api/ run dev &

# Router Bootstrapping
npm --prefix ./services/socket/ run dev &

# GPU Bootstrapping
cd ./services/gpu/
python3 -m venv venv
source ./venv/bin/activate

export API='http://localhost:2000'
export SOCKET='http://localhost:1999'
python worker.py

wait
