{{- if .Values.placeholder.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "lulc-helm.fullname" . }}-prepull
spec:
  selector:
    matchLabels:
      name: {{ template "lulc-helm.fullname" . }}-prepull
  template:
    metadata:
      labels:
        name: {{ template "lulc-helm.fullname" . }}-prepull
    spec:
      nodeSelector:
        agentpool: {{ .Values.placeholder.nodeSelectorName }}
      initContainers:
      - name: init-puller
        image: "{{ .Values.gpu.image.name }}:{{ .Values.gpu.image.tag }}"
        command: ["/bin/bash"]
        args: ["-c", "echo", "prepull done!"]
      containers:
      - name: pause
        image: gcr.io/google_containers/pause:latest
{{- end }}
