{{- if .Values.placeholder.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: placeholder
value: 0
preemptionPolicy: Never
globalDefault: false
description: 'placeholder'
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal
value: 1
preemptionPolicy: PreemptLowerPriority
globalDefault: true
description: 'normal'
{{- end }}