{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lulc-helm.fullname" . }}-api
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lulc-helm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ template "lulc-helm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-api
    spec:
      serviceAccountName: kubesurfer
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: agentpool
                  operator: NotIn
                  values:
                    - "gpunodepool"
                    - "tiler"
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          command: ["/bin/sh"]
          args: ["-c", "while true; do npx knex migrate:latest && npm run prod; sleep 10;done"]
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/
              port: {{ .Values.api.containerPort }}
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
          env:
            - name: SigningSecret
              value: {{ .Values.api.env.SigningSecret }}
            - name: Postgres
              value: {{ .Values.api.env.Postgres }}
            - name: GpuImageName
              value: {{ .Values.gpu.image.name }}
            - name: GpuImageTag
              value: {{ .Values.gpu.image.tag }}
            - name: GpuCount
              value: {{ .Values.api.env.GpuCount | quote }}
            - name: AZURE_STORAGE_CONNECTION_STRING
              value: {{ .Values.api.env.AZURE_STORAGE_CONNECTION_STRING}}
            - name: Deployment
              value: {{ template "lulc-helm.fullname" . }}
            - name: TileUrl
              value: http://{{ template "lulc-helm.fullname" . }}-tiles
            - name: ApiUrl
              value: https://api.{{ .Values.domain }}
            - name: SocketUrl
              value: ws://{{ template "lulc-helm.fullname" . }}-socket
            - name: nodeSelectorKey
              value: {{ .Values.api.env.nodeSelectorKey }}
            - name: nodeSelectorValue
              value: {{ .Values.api.env.nodeSelectorValue }}
{{- end }}
