version: '3'

services:
  tiler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cache
    ports:
    - "8000:8000"
    environment:
      - PORT=8000
      - MOSAIC_BACKEND=sqlite:///
      - MOSAIC_HOST=/tmp/data/mosaics.db
      - CACHE_ENDPOINT=redis://host.docker.internal:6379

  cache:
    image: redis:latest
    ports:
      - 6379:6379

