kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "lulc-helm.fullname" . }}-kubejanitor
  labels:
    app: {{ template "lulc-helm.name" . }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "lulc-helm.fullname" . }}-kubejanitor
subjects:
- kind: ServiceAccount
  name: {{ template "lulc-helm.fullname" . }}-kubejanitor
  namespace: {{ .Release.Namespace }}
