environment: prod
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  env:
    SigningSecret: {{PRODUCTION_SIGNING_SECRET}}
    Postgres: {{PRODUCTION_POSTGRES}}
socket:
  enabled: true
  containerPort: 1999
tiles:
  enabled: true
  replicaCount: 1
  containerPort: 8000
  env:
    Backends: {{PRODUCTION_MOSAIC_BACKEND}}
    Host: {{PRODUCTION_MOSAIC_HOST}}
    WebConcurrency: 2
