environment: dev
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  image:
    name: 'developmentseed/lulc-api'
    tag: '0.0.1-n060.h82d2bb3'
gpu:
  enabled: true
  image:
    name: 'developmentseed/lulc-gpu'
    tag: '0.0.1-n060.h82d2bb3'
