environment: dev
domain: lulc-staging.ds.io
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  env:
    SigningSecret: {{STAGING_SIGNING_SECRET}}
    Postgres: {{STAGING_POSTGRES}}
    AZURE_STORAGE_CONNECTION_STRING: {{STAGING_AZURE_STORAGE_CONNECTION_STRING}}
    GpuCount: 8
socket:
  enabled: true
  containerPort: 1999
tiles:
  enabled: true
  replicaCount: 2
  containerPort: 8000
  env:
    Debug: TRUE
    Backends: {{STAGING_MOSAIC_BACKEND}}
    Host: {{STAGING_MOSAIC_HOST}}
    WebConcurrency: 2

placeholder:
  enabled: true
  replicaCount: 1
  nodeSelectorName: gpunodepool
  isGpu: true

tilesScaler:
  env:
    backendPool: pool-default-lulc-staging-lulc-helm-tiles-80-bp-8000~bp-default-lulc-staging-lulc-helm-tiles-80-8000-029e669b1fed84821a79034b9b2e4ee9
    tenantId: {{STAGING_TENANT_ID}}
    subscriptionId: {{STAGING_SUBSCRIPTION_ID}}
    resourceGroupName: {{CLUSTER_RESOURCE_GROUP}}
    activeDirectoryClientId: {{STAGING_CLIENT_ID}}
    activeDirectoryClientPassword: {{STAGING_CLIENT_SECRET}}
# ingress-azure:
#   appgw:
#     subscriptionId: {{STAGING_APPGW_SUBSCRIPTION_ID}}
#     resourceGroup: {{STAGING_APPGW_RESOURCE_GROUP}}
#     name: {{STAGING_APPGW_NAME}}
#   armAuth:
#      type: servicePrincipal
#      secretJSON: {{STAGING_SERVICE_PRINCIPAL_BASE64}}
