environment: dev
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
socket:
  enabled: true
  containerPort: 1999
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
tiles:
  enabled: true
  replicaCount: 1
  containerPort: 8000
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
  nodeSelector:
    enabled: true
    label_key: agentpool
    label_value: nodepool1
  resources:
    requests:
      cpu: 1
      memory: "1Gi"
    limits:
      cpu: 1
      memory: "1Gi"
