environment: prod
domain: lulc.ds.io
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  env:
    SigningSecret: {{STAGING_SIGNING_SECRET}}
    Postgres: {{PRODUCTION_POSTGRES}}
    AZURE_STORAGE_CONNECTION_STRING: {{PRODUCTION_AZURE_STORAGE_CONNECTION_STRING}}
    nodeSelectorKey: 'agentpool'
    nodeSelectorValue: 'tiler'
socket:
  enabled: true
  containerPort: 1999
tiles:
  enabled: true
  replicaCount: 2
  containerPort: 8000
  env:
    Debug: TRUE
    Backends: {{STAGING_MOSAIC_BACKEND}}
    Host: {{STAGING_MOSAIC_HOST}}
    WebConcurrency: 2
tilesScaler:
  env:
    backendPool: pool-default-lulc-production-lulc-helm-tiles-80-bp-8000~bp-default-lulc-production-lulc-helm-tiles-80-8-374794b60d6d018518c60d63627773ba
    tenantId: {{STAGING_TENANT_ID}}
    subscriptionId: {{STAGING_SUBSCRIPTION_ID}}
    resourceGroupName: {{CLUSTER_RESOURCE_GROUP}}
    activeDirectoryClientId: {{PRODUCTION_CLIENT_ID}}
    activeDirectoryClientPassword: {{PRODUCTION_CLIENT_SECRET}}

# This is now run manually on the cluster
# ingress-azure:
#   appgw:
#     subscriptionId: {{STAGING_APPGW_SUBSCRIPTION_ID}}
#     resourceGroup: {{STAGING_APPGW_RESOURCE_GROUP}}
#     name: {{STAGING_APPGW_NAME}}
#   armAuth:
#      type: servicePrincipal
#      secretJSON: {{STAGING_SERVICE_PRINCIPAL_BASE64}}
