environment: dev
api:
  enabled: true
  replicaCount: 1
  containerPort: 2000
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
socket:
  enabled: true
  containerPort: 1999
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
tiles:
  enabled: true
  replicaCount: 1
  containerPort: 8000
  image:
    name: 'chartpress_replace'
    tag: 'chartpress_replace'
