name: landcover

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python>=3.6
  - gdal>=2.0  # if solving environment is taking too longer, specify the version of gdal to proceed faster (gdal==2.4.3)
  - rasterio
  - shapely
  - rtree
  - fiona
  - opencv
  - proj4
  - numpy
  - matplotlib
  - scikit-learn
  - scikit-image
  - pytorch>=1.0
  - torchvision
  - utm
  - bottle==0.12.18
  - beaker==1.11.0
  - cheroot==8.3.0
  - joblib
  - mercantile
  - ipykernel
  - pylint
  - pip
  - pip:
    - tensorflow
    - rpyc  