{{- if .Values.nginx.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "lulc-helm.fullname" . }}-ingress-nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-issuer
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - {{ .Values.nginx.frontendDomain }}
      secretName: {{ template "lulc-helm.fullname" . }}-secret-nginx

  rules:
  - host: {{ .Values.nginx.frontendDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "lulc-helm.fullname" . }}-nginx
            port:
              number: 80
{{- end }}
