{{- if .Values.gpu.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "lulc-helm.fullname" . }}-gpu
  labels:
    component: gpu-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.gpu.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "lulc-helm.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-gpu
  template:
    metadata:
      labels:
        app: {{ template "lulc-helm.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-gpu
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-gpu
          image: "{{ .Values.gpu.image.name }}:{{ .Values.gpu.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.gpu.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.gpu.containerPort }}
          env:
            - name: EXAMPLE_ENV
              value: dummy_value

{{- end }}