#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0") --dev
Deploys the staging infrastructure.

--console: Don't run deploy; drop into a console in the deploy container
--dev: Include this flag to deploy a dev stack.
    To do so you'll need to set the necessary environment
    variables; see README.
"
}

while [[ "$#" > 0 ]]; do case $1 in
    --dev)
        ENVIRONMENT=dev
        shift
        ;;
    --staging)
        ENVIRONMENT=staging
        shift
        ;;
    --production)
        ENVIRONMENT=production
        shift
        ;;
    --help)
        usage
        exit 0
        shift
        ;;
    *)
        usage "Unknown parameter passed: $1"
        shift
        shift
        ;;
    esac done

DOCKER_COMPOSE="docker-compose -f deployment/docker-compose.yml"

echo "Setting terraform directory to $ENVIRONMENT"

TERRAFORM_DIR=/opt/src/terraform/${ENVIRONMENT}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then

    (
        # Set git commit
        GIT_COMMIT="$(git rev-parse --short HEAD)"
        export GIT_COMMIT

        # Build deployment container
        ${DOCKER_COMPOSE} build

        # Run deployment script
        ${DOCKER_COMPOSE} run --rm \
            deploy bin/deploy \
            -t "${TERRAFORM_DIR}"
    )
fi
