#!/bin/bash

set -e

if [[ "${CI}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
CI publish for this project.

"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    chartpress --push
fi
