charts:
  - name: pearl-helm
    imagePrefix: lulcterraformacr.azurecr.io/lulc-
    repo:
       git: developmentseed/pearl-helm-chart
       published: https://devseed.com/pearl-helm-chart

    images:
      api:
        valuesPath: api.image
        contextPath: ../../services/api/
        dockerfilePath: ../../services/api/Dockerfile
      socket:
        valuesPath: socket.image
        contextPath: ../../services/socket/
        dockerfilePath: ../../services/socket/Dockerfile
      tiles:
        valuesPath: tiles.image
        contextPath: ../../services/tiles/
        dockerfilePath: ../../services/tiles/Dockerfile
      gpu:
        valuesPath: gpu.image
        contextPath: ../../services/gpu/
        dockerfilePath: ../../services/gpu/Dockerfile
      nginx:
        valuesPath: nginx.image
        contextPath: ../../services/nginx-redirect
        dockerfilePath: ../../services/nginx-redirect/Dockerfile
