name: GPU Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Docker Pull
        run: docker-compose pull

      - name: Docker GPU Build
        run: docker build -t gpu services/gpu

      - name: Docker API GPU Lint
        run: docker run gpu sh -c "python -m py_compile worker.py"
