name: Lint

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    build:
        runs-on: ubuntu-20.04
        if: github.event.pull_request.draft == false
        timeout-minutes: 30
        steps:
            - uses: actions/checkout@v1

            - name: Docker API Build
              run: docker build -t api services/api

            - name: Docker API Lint
              run: docker run api sh -c "npm install --include=dev && npm run lint"

            - name: Docker GPU Build
              run: docker build -t gpu services/gpu

            - name: Docker API GPU Lint
              run: docker run gpu sh -c "python -m py_compile worker.py"

