name: Socket Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  test:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Docker Pull
        run: docker-compose pull

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@46d2c640b1d8ef50d185452ad6fb324e6bd1d052 # v0.0.11
        continue-on-error: true

      - name: Docker Socket Build
        run: docker build -t socket services/socket

      - name: Docker Socket Lint
        run: docker run socket sh -c "npm install --include=dev && npm run lint"


