name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 120
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.LULCDATA_ASCS }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Docker Pull
        run: docker-compose pull

      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
         node-version: 18

      - name: Run Test
        run: ./scripts/test
