name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 60
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.LULCDATA_ASCS }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Pull
        run: docker-compose pull

      - name: Run Test
        run: ./scripts/test
