name: Test

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Docker Build
              run: docker-compose build

            - name: Docker Test Build
              run: docker build -t test .
