name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Docker Pull
        run: docker-compose pull

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run Test
        run: ./scripts/test
